let mock = [
  {
    id: 1,
    name: "Astral Kuriboh",
    Attribute: "LIGHT",
    ATK: 100,
    DEF: 100,
    image: "AstralKuriboh.jpg",
  },
  {
    id: 2,
    name: "Chronomaly Tuspa Rocket",
    Attribute: "EARTH",
    ATK: 1000,
    DEF: 1000,
    image: "Chronomaly Tuspa Rocket.jpg",
  },
  {
    id: 3,
    name: "CXyz Barian Hope",
    Attribute: "LIGHT",
    ATK: 0,
    DEF: 0,
    image: "CXyz Barian Hope.jpg",
  },
  {
    id: 4,
    name: "Galaxy Satellite Dragon",
    Attribute: "DARK",
    ATK: 2000,
    DEF: "-",
    image: "Galaxy Satellite Dragon.jpg",
  },
  {
    id: 5,
    name: "Galaxy-Eyes Afterglow Dragon",
    Attribute: "LIGHT",
    ATK: 3000,
    DEF: 2500,
    image: "Galaxy-Eyes Afterglow Dragon.jpg",
  },
  {
    id: 6,
    name: "Number 100: Numeron Dragon",
    Attribute: "LIGHT",
    ATK: 0,
    DEF: 0,
    image: "Number100NumeronDragon.jpg",
  },
  {
    id: 7,
    name: "Numeral Hunter",
    Attribute: "LIGHT",
    ATK: 1600,
    DEF: 1400,
    image: "Numeral Hunter.jpg",
  },
  {
    id: 8,
    name: "Astraltopia",
    Attribute: "LIGHT",
    ATK: 0,
    DEF: 0,
    image: "Astraltopia.jpg",
  },
  {
    id: 9,
    name: "Arc Rebellion Xyz Dragon",
    Attribute: "DARK",
    ATK: 3000,
    DEF: 2500,
    image: "Arc Rebellion Xyz Dragon.jpg",
  },
  {
    id: 10,
    name: "Black Fang Magician",
    Attribute: "DARK",
    ATK: 1700,
    DEF: 800,
    image: "Black Fang Magician.jpg",
  },
  {
    id: 11,
    name: "Chronograph Sorcerer",
    Attribute: "DARK",
    ATK: 2000,
    DEF: 1700,
    image: "Chronograph Sorcerer.jpg",
  },
  {
    id: 12,
    name: "Samurai Cavalry of Reptier",
    Attribute: "EARTH",
    ATK: 1800,
    DEF: 1200,
    image: "Samurai Cavalry of Reptier.jpg",
  },
  {
    id: 13,
    name: "Performapal Secondonkey",
    Attribute: "EARTH",
    ATK: 1000,
    DEF: 2000,
    image: "Performapal Secondonkey.jpg",
  },
  {
    id: 14,
    name: "Performapal Splashmammoth",
    Attribute: "WATER",
    ATK: 1900,
    DEF: 2300,
    image: "Performapal Splashmammoth.jpg",
  },
  {
    id: 15,
    name: "Performapal Helpprincess",
    Attribute: "DARK",
    ATK: 1200,
    DEF: 1200,
    image: "Performapal Helpprincess.jpg",
  },
  {
    id: 16,
    name: "Superheavy Samurai Thief",
    Attribute: "EARTH",
    ATK: 1000,
    DEF: 1000,
    image: "Superheavy Samurai Thief.jpg",
  },
  {
    id: 17,
    name: "Superheavy Samurai Transporter",
    Attribute: "EARTH",
    ATK: 1200,
    DEF: 1800,
    image: "Superheavy Samurai Transporter.jpg",
  },
  {
    id: 18,
    name: "Superheavy Samurai Drum",
    Attribute: "EARTH",
    ATK: 300,
    DEF: 300,
    image: "Superheavy Samurai Drum.jpg",
  },
  {
    id: 19,
    name: "Superheavy Samurai Soulhorns",
    Attribute: "EARTH",
    ATK: 0,
    DEF: 300,
    image: "Superheavy Samurai Soulhorns.jpg",
  },
  {
    id: 20,
    name: "Fluffal Wings",
    Attribute: "LIGHT",
    ATK: 100,
    DEF: 100,
    image: "Fluffal Wings.jpg",
  },
];

export default mock;
